<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>scopeName</key>
		<string>text.log</string>

		<key>fileTypes</key>
		<array>
			<string>log</string>
		</array>

		<key>name</key>
		<string>Log file</string>

		<key>patterns</key>
		<array>
			<!-- DEBUG -->
			<dict>
				<key>match</key>
				<string>\b(DEBU.*)\b|(?i)\b(debu.*)\:</string>
				<key>name</key>
				<string>markup.deleted</string>
			</dict>

			<!-- WARN -->
			<dict>
				<key>match</key>
				<string>\b(WARN.*)\b|(?i)\b(warn.*)\:</string>
				<key>name</key>
				<string>meta.selector</string>
			</dict>

			<!-- ERROR -->
			<dict>
				<key>match</key>
				<string>\b(ERRO.*)\b|(?i)\b(erro.*)\:</string>

				<key>name</key>
				<string>invalid</string>
			</dict>

			<!-- NOTE -->
			<dict>
				<key>match</key>
				<string>\b(NOTE.*)\b|(?i)\b(note.*)\:</string>

				<key>name</key>
				<string>constant.language</string>
			</dict>

			<!-- Set Up -->
			<dict>
				<key>match</key>
				<string>set\Kup</string>
				<key>name</key>
				<string>markup.changed</string>
			</dict>

			<!-- ARROW -->
			<dict>
				<key>match</key>
				<string><-|-></string>
				<key>name</key>
				<string>markup.bold</string>
			</dict>


			<!-- TIMESTAMP -->
			<dict>
				<key>match</key>
				<string>\[\d{10}\]</string>
				<key>name</key>
				<string>comment</string>
			</dict>
			
			<!-- SET STATE -->
			<dict>
				<key>match</key>
				<string>READER_\S+</string>
				<key>name</key>
				<string>constant.language</string>
			</dict>
		</array>
		
		<key>uuid</key>
		<string>E81BB6AB-CAC7-4C27-9A79-4137A4693EBD</string>
	</dict>
</plist>
